### ISSUE TITLE
Sidebar for heading navigations

### ISSUE THREAD

**Issue by anthonyshew** [anthonyshew/repo#29]
Going to be essentially the same exact thing as this! It will involved parsing the Markdown, looking for lines that start with `#`, `##`, `###`, etc. and then rendering the links to those.

![CleanShot 2023-08-13 at 18 15 48@2x](https://github.com/anthonyshew/maestros/assets/35677084/8fd6fbac-bdc6-4669-9487-5a20b8623946)

**Comment by AidanLaycock** [comment]
As a minor additional improvement with this, it might be worth adding the `#` icon or something similar for headings, so that when someone hovers over it they can see that it will be added to the URL for direct linking. (It's currently an underline anchor tag, it works the same way, it's just not as visually intuitive).
